'use client'
import Link from 'next/link'
import {useState} from 'react'
import {ChevronLeft,Info,Map,Menu,X} from 'lucide-react'
import {destinations,type OnaDestination} from '@/data/spatial'
import {useExperience} from './ExperienceState'
const mapItems:OnaDestination[]=['masterplan','tower-01','tower-02','commercial','community','parking','location']

export function SpatialInterface(){
 const{destination,navigateTo,goBack,view,setView}=useExperience()
 const[map,setMap]=useState(false);const[info,setInfo]=useState(false)
 const current=destinations[destination];const trail:typeof current[]=[];let cursor:typeof current|undefined=current
 while(cursor){trail.unshift(cursor);cursor=cursor.parent?destinations[cursor.parent]:undefined}
 const entered=destination!=='arrival'
 return <div className="pointer-events-none absolute inset-0 z-30 text-bone">
  <header className="flex items-center justify-between p-5 md:p-8"><button onClick={()=>navigateTo('masterplan')} className="pointer-events-auto text-left font-display text-2xl leading-none">ONA<span className="block font-sans text-[7px] tracking-[.35em]">TOWERS</span></button><div className="pointer-events-auto flex items-center gap-4 text-[9px] uppercase tracking-[.15em]">{entered?<><button onClick={()=>setMap(!map)} className="hidden items-center gap-2 md:flex"><Map size={14}/> Map</button><button onClick={()=>navigateTo('residence-2br')} className="hidden md:block">Find a home</button><button onClick={()=>navigateTo('enquiry')}>Enquire</button><button onClick={()=>setInfo(!info)} aria-label="Project information"><Menu size={18}/></button></>:<><Link href="/guided" className="hidden md:block">Guided tour</Link><button onClick={()=>navigateTo('enquiry')}>Enquire</button></>}</div></header>
  {entered&&<div className="absolute left-5 top-24 md:left-8"><p className="text-[8px] uppercase tracking-[.22em] text-bone/45">You are here</p><div className="mt-2 flex flex-wrap items-center gap-2 text-[9px] uppercase tracking-[.14em]">{trail.map((item,i)=><span key={item.id} className="flex items-center gap-2">{i>0&&<span className="text-bone/30">/</span>}{item.label}</span>)}</div></div>}
  {destination==='masterplan'&&<div className="pointer-events-auto absolute bottom-20 left-5 w-[min(390px,calc(100vw-2.5rem))] border-l border-hairline bg-charcoal/80 p-5 backdrop-blur-md md:bottom-8 md:left-8 md:p-7"><p className="text-[8px] uppercase tracking-[.24em] text-hairline">Explore ONA</p><h2 className="mt-3 font-display text-3xl">The development is your map.</h2><p className="mt-3 max-w-sm text-[10px] leading-relaxed text-bone/55">Select the towers and buildings directly, or choose a destination below.</p><div className="mt-5 flex flex-wrap gap-x-5 gap-y-2 text-[9px] uppercase tracking-widest"><button onClick={()=>navigateTo('tower-01')}>Enter Tower 01 →</button><button onClick={()=>navigateTo('commercial')}>Commercial →</button><button onClick={()=>navigateTo('location')}>Zanzibar →</button></div></div>}
  {entered&&destination!=='masterplan'&&<div className="absolute bottom-5 left-5 flex items-center gap-3 md:bottom-8 md:left-8"><button onClick={()=>setMap(!map)} className="pointer-events-auto flex items-center gap-2 border border-bone/25 bg-charcoal/55 px-4 py-2 text-[9px] uppercase tracking-widest backdrop-blur"><Map size={13}/> ONA Map</button><button onClick={goBack} className="pointer-events-auto flex items-center gap-2 text-[9px] uppercase tracking-widest"><ChevronLeft size={13}/> Back</button></div>}
  {entered&&destination!=='masterplan'&&<div className="absolute bottom-5 right-5 text-right md:bottom-8 md:right-8"><p className="text-[8px] uppercase tracking-[.2em] text-hairline">{current.label}</p><p className="mt-2 max-w-xs font-display text-2xl leading-none md:text-3xl">{current.context}</p>{current.description&&<p className="mt-3 max-w-xs text-[10px] text-bone/55">{current.description}</p>}<div className="pointer-events-auto mt-4 flex justify-end gap-3 text-[8px] uppercase tracking-widest"><span className="text-bone/40">View</span>{(['aerial','building','ground'] as const).map(item=><button className={view===item?'border-b border-hairline':'text-bone/45'} onClick={()=>setView(item)} key={item}>{item}</button>)}</div></div>}
  {map&&<div className="pointer-events-auto absolute inset-x-5 bottom-20 border border-bone/20 bg-charcoal/95 p-6 backdrop-blur md:bottom-20 md:left-8 md:right-auto md:w-[420px]"><button onClick={()=>setMap(false)} className="absolute right-4 top-4"><X size={16}/></button><p className="text-[9px] uppercase tracking-[.2em] text-bone/45">ONA Map</p><div className="mt-6 grid grid-cols-2 gap-px bg-bone/15">{mapItems.map(id=><button onClick={()=>{navigateTo(id);setMap(false)}} key={id} className={`bg-charcoal p-4 text-left text-xs ${destination===id?'text-hairline':'text-bone'}`}>{destinations[id].label}</button>)}</div></div>}
  {info&&<div className="pointer-events-auto absolute right-5 top-20 w-[min(420px,calc(100vw-2.5rem))] border border-bone/20 bg-charcoal/95 p-7 backdrop-blur md:right-8"><button onClick={()=>setInfo(false)} className="absolute right-4 top-4"><X size={16}/></button><Info size={17}/><h2 className="mt-8 font-display text-4xl">Project information</h2><div className="mt-7 space-y-3 text-xs text-bone/65"><p>2 residential towers</p><p>11 residential floors</p><p>Approximately 46 residences per tower</p><p>2 & 3 bedroom homes · signature penthouses</p><p>Commercial / service component</p></div><p className="mt-7 border-t border-bone/15 pt-5 text-[9px] text-bone/40">Brochure and final residence plans will be connected here once approved for release.</p></div>}
 </div>
}
