'use client'
import {motion} from 'framer-motion'
import {Media} from '@/components/ui/Media'
import {useExperience} from './ExperienceState'

export function SceneLayers(){const{destination,navigateTo}=useExperience();if(destination==='floor-08')return <motion.div initial={{opacity:0,scale:.8}} animate={{opacity:1,scale:1}} className="absolute inset-[16%] z-10 rotate-[-2deg] border border-bone/40 bg-charcoal/90 p-4 shadow-2xl md:inset-[18%_20%]"><div className="grid h-full grid-cols-2 grid-rows-2 gap-2"><button onClick={()=>navigateTo('residence-2br')} className="group relative border border-hairline/60 bg-stone/10 text-bone hover:bg-bone/15"><span className="text-xs uppercase tracking-widest">2 Bedroom<br/><small>203 m² · Ocean orientation</small></span></button><button className="border border-bone/25 text-bone/55"><span className="text-xs uppercase tracking-widest">3 Bedroom<br/><small>236 m²</small></span></button><button className="border border-bone/25 text-bone/55"><span className="text-xs uppercase tracking-widest">2 Bedroom<br/><small>203 m² · Sunrise orientation</small></span></button><button className="border border-bone/25 text-bone/55"><span className="text-xs uppercase tracking-widest">3 Bedroom<br/><small>236 m²</small></span></button></div></motion.div>
  if(destination==='residence-2br'||destination==='plan-transformation')return <motion.div initial={{opacity:0}} animate={{opacity:1}} className="absolute inset-0 z-10 bg-charcoal"><Media src="/placeholders/blueprint-2br.svg" alt="Two bedroom conceptual floor plan" className="h-full opacity-90"/><motion.div className="absolute inset-0" initial={{clipPath:'inset(0 100% 0 0)'}} animate={{clipPath:destination==='plan-transformation'?'inset(0 0% 0 0)':'inset(0 100% 0 0)'}} transition={{duration:1.5,ease:[.22,1,.36,1]}}><Media src="/placeholders/residence-01.svg" alt="Two bedroom finished interior concept" className="h-full"/></motion.div><div className="absolute inset-0 bg-gradient-to-t from-charcoal/75 via-transparent to-transparent"/><div className="absolute bottom-24 left-6 md:left-[7vw]"><p className="text-[10px] uppercase tracking-[.22em] text-bone/60">Two Bedroom · 203 m²</p><button onClick={()=>navigateTo(destination==='residence-2br'?'plan-transformation':'interior')} className="mt-5 border-b border-hairline pb-1 text-xs uppercase tracking-widest text-bone">{destination==='residence-2br'?'Transform plan →':'Step inside →'}</button></div></motion.div>
  if(destination==='interior')return <motion.div initial={{opacity:0,scale:1.08}} animate={{opacity:1,scale:1}} transition={{duration:1.4}} className="absolute inset-0 z-10 bg-charcoal"><Media src="/placeholders/residence-01.svg" alt="ONA living room interior concept" className="h-full"/><div className="absolute inset-0 bg-gradient-to-t from-charcoal/65 via-transparent to-charcoal/20"/><div className="absolute bottom-24 left-6 md:left-[7vw]"><p className="text-[10px] uppercase tracking-[.2em] text-bone/60">Living Room · Concept Interior</p><h2 className="mt-3 max-w-2xl font-display text-5xl text-bone md:text-7xl">Where living becomes a view.</h2></div></motion.div>
  if(destination==='location')return <motion.div initial={{opacity:0}} animate={{opacity:1}} className="absolute inset-0 z-10 bg-stone"><div className="absolute -inset-y-[30%] -left-[20%] w-[65%] rounded-[48%] bg-graphite"/><div className="absolute inset-0 opacity-20 [background-image:repeating-linear-gradient(35deg,transparent_0_100px,currentColor_101px_102px)]"/><div className="absolute left-[58%] top-[52%] size-4 rounded-full border border-hairline bg-charcoal shadow-[0_0_0_12px_rgba(52,49,44,.15)]"/><p className="absolute left-[calc(58%+2rem)] top-[50%] text-[10px] uppercase tracking-widest">ONA Towers</p><p className="absolute bottom-20 left-6 max-w-lg text-sm text-graphite/60 md:left-[7vw]">Surrounding geography and verified connections will be added from the confirmed project location data.</p></motion.div>
  return null}
