import {CampaignHeader} from './CampaignHeader'
import {CinematicHero} from './CinematicHero'
import {DevelopmentSection,VisionSection} from './VisionDevelopment'
import {PenthouseChapter,ResidenceTypes,ResidencesIntro} from './ResidenceSections'
import {InteriorsStory,LifestyleStory} from './VisualStories'
import {ArchitectureFacts,CommercialStory} from './CommercialFacts'
import {CampaignEnquiry,CampaignFooter,LocationSection} from './EndSections'
import {CommercialTerraceOverview,TypicalFloorOverview} from './PlanOverviews'
export function OnaCampaign(){return <><CampaignHeader/><CinematicHero/><VisionSection/><DevelopmentSection/><ResidencesIntro/><ResidenceTypes/><TypicalFloorOverview/><PenthouseChapter/><InteriorsStory/><LifestyleStory/><CommercialStory/><CommercialTerraceOverview/><ArchitectureFacts/><LocationSection/><CampaignEnquiry/><CampaignFooter/></>}
