'use client'
import Image from 'next/image'
import {AnimatePresence,motion} from 'framer-motion'
import {useState} from 'react'
import {cinematicAssets} from '@/data/cinematic'
import {Reveal} from '@/components/ui/Reveal'
const ideas=[{word:'LIVE',label:'01 / LIVE',title:'A home above the everyday.',line:'Generous residences shaped around space, light and outlook.',image:cinematicAssets.residences.tower,target:'residences'},{word:'LIFE',label:'02 / LIFE',title:'More than an address.',line:'Rooftop experiences bring the community into view.',image:cinematicAssets.lifestyle.pool,target:'lifestyle'},{word:'WORK',label:'03 / WORK',title:'Business, closer to life.',line:'A commercial address within the rhythm of ONA.',image:cinematicAssets.commercial.boardroom,target:'commercial'}]
export function VisionSection(){const[active,setActive]=useState(0);return <section id="vision" className="bg-bone text-graphite"><div className="page-shell py-24 md:grid md:grid-cols-[34%_66%] md:gap-10 md:py-0"><div className="top-0 flex h-[62svh] flex-col justify-center md:sticky md:h-[100svh]"><p className="text-[8px] uppercase tracking-[.22em] text-hairline">THE ONA IDEA</p><AnimatePresence mode="wait"><motion.div key={active} initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}} transition={{duration:.5}}><p className="mt-7 text-[10px] uppercase tracking-[.22em] text-graphite/40">{ideas[active].label}</p><h2 className="mt-2 font-display text-[clamp(4.5rem,9vw,8.5rem)] font-light leading-[.8]">{ideas[active].word}</h2><h3 className="mt-7 max-w-sm font-display text-3xl leading-none md:text-4xl">{ideas[active].title}</h3><p className="mt-4 max-w-xs text-xs leading-6 text-graphite/55">{ideas[active].line}</p></motion.div></AnimatePresence></div><div>{ideas.map((idea,index)=><motion.article key={idea.word} onViewportEnter={()=>setActive(index)} viewport={{amount:.55}} className="flex min-h-[88svh] items-center py-8"><button onClick={()=>document.getElementById(idea.target)?.scrollIntoView({behavior:'smooth'})} className="group block w-full text-left"><div className="relative aspect-[4/5] overflow-hidden md:aspect-[1.05]"><Image src={idea.image} alt={`${idea.word}: ${idea.title}`} fill sizes="(min-width:768px) 63vw, 100vw" className="object-cover transition-transform duration-[1400ms] group-hover:scale-[1.015]"/></div><div className="mt-4 flex justify-between border-t border-graphite/15 pt-3 text-[7px] uppercase tracking-[.18em]"><span>{idea.label}</span><span>Discover →</span></div></button></motion.article>)}</div></div><Reveal className="border-y border-graphite/15 py-16 text-center"><p className="text-[9px] uppercase tracking-[.28em] text-hairline">Live &nbsp; / &nbsp; Life &nbsp; / &nbsp; Work</p><h3 className="mt-5 font-display text-4xl md:text-6xl">One connected destination.</h3></Reveal></section>}
const markers=[{label:'Tower A',position:'left-[22%] top-[30%]',target:'residences'},{label:'Tower B',position:'right-[25%] top-[27%]',target:'residences'},{label:'Commercial / Lifestyle',position:'left-[47%] bottom-[27%]',target:'commercial'}]
export function DevelopmentSection(){return <section id="development" className="bg-[#FAF8F3] py-28 text-graphite md:py-40"><div className="page-shell"><Reveal><p className="eyebrow text-hairline">THE DEVELOPMENT</p><h2 className="display max-w-5xl text-5xl md:text-8xl">How the ONA idea comes together.</h2><p className="mt-6 max-w-lg text-sm text-graphite/55">Two residential towers and a connected commercial and lifestyle address.</p></Reveal><Reveal className="relative mt-16 aspect-[4/5] bg-bone md:aspect-[1.7]" delay={.1}><Image src={cinematicAssets.masterplan} alt="ONA Towers development masterplan" fill sizes="94vw" className="object-contain mix-blend-multiply"/>{markers.map((marker,index)=><button key={marker.label} onClick={()=>document.getElementById(marker.target)?.scrollIntoView({behavior:'smooth'})} className={`group absolute ${marker.position} grid size-8 place-items-center rounded-full border border-hairline bg-bone/95 text-[8px] focus:ring-2 focus:ring-hairline`} aria-label={`Go to ${marker.label}`}><span>{index+1}</span><span className="absolute left-1/2 top-full mt-2 hidden -translate-x-1/2 whitespace-nowrap bg-graphite px-3 py-2 text-[7px] uppercase tracking-[.14em] text-bone group-hover:block group-focus:block">{marker.label}</span></button>)}</Reveal><div className="mt-5 flex flex-wrap gap-6 text-[8px] uppercase tracking-[.18em] md:hidden">{markers.map(marker=><button key={marker.label} onClick={()=>document.getElementById(marker.target)?.scrollIntoView({behavior:'smooth'})}>{marker.label} →</button>)}</div></div></section>}
