'use client'
import Image from 'next/image'
import {useEffect,useRef,useState} from 'react'
import {AnimatePresence,motion} from 'framer-motion'
import {Maximize2,Minus,Plus,X} from 'lucide-react'
import {cinematicAssets,residenceTypes} from '@/data/cinematic'
import {Reveal} from '@/components/ui/Reveal'
type Residence=typeof residenceTypes[number]
function PlanViewer({item,onClose}:{item:Residence;onClose:()=>void}){const[zoom,setZoom]=useState(1);const close=useRef<HTMLButtonElement>(null);useEffect(()=>{close.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose()};addEventListener('keydown',key);document.body.style.overflow='hidden';return()=>{removeEventListener('keydown',key);document.body.style.overflow=''}},[onClose]);return <motion.div role="dialog" aria-modal="true" aria-label={`${item.label} floor plan`} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[80] bg-bone text-graphite"><div className="absolute inset-x-0 top-0 z-20 flex items-center justify-between border-b border-graphite/15 p-5"><div><p className="text-[8px] uppercase tracking-[.2em] text-hairline">FLOOR PLAN</p><h2 className="font-display text-2xl">{item.label}</h2></div><div className="flex items-center gap-2"><button onClick={()=>setZoom(v=>Math.max(1,v-.25))} className="grid size-9 place-items-center border border-graphite/20" aria-label="Zoom out"><Minus size={14}/></button><button onClick={()=>setZoom(v=>Math.min(2.5,v+.25))} className="grid size-9 place-items-center border border-graphite/20" aria-label="Zoom in"><Plus size={14}/></button><button ref={close} onClick={onClose} className="grid size-9 place-items-center bg-graphite text-bone" aria-label="Close plan"><X size={15}/></button></div></div><div className="absolute inset-x-0 bottom-16 top-20 overflow-auto p-5"><div style={{transform:`scale(${zoom})`}} className="relative mx-auto h-full w-full origin-center transition-transform"><Image src={item.plan} alt={`${item.label} architectural plan`} fill sizes="95vw" className="object-contain mix-blend-multiply"/></div></div><p className="absolute bottom-5 left-5 text-[8px] uppercase tracking-[.14em] text-graphite/45">{item.meta} · {item.note}</p></motion.div>}
export function ResidencesIntro(){return <section id="residences" className="relative min-h-[100svh] overflow-hidden bg-charcoal text-bone"><Image src={cinematicAssets.residences.tower} alt="ONA residential tower exterior visualization" fill sizes="100vw" className="object-cover object-center opacity-85"/><div className="absolute inset-0 bg-gradient-to-r from-charcoal/85 via-charcoal/20 to-transparent"/><Reveal className="absolute bottom-[10svh] left-5 max-w-xl md:left-[7vw]"><p className="eyebrow text-hairline">01 / RESIDENCES</p><h2 className="display text-6xl md:text-9xl">Live above.</h2><p className="mt-6 max-w-sm text-sm text-bone/65">Generous residences shaped around light, outlook and everyday life in Zanzibar.</p></Reveal></section>}
export function ResidenceTypes(){const[open,setOpen]=useState<Residence|null>(null);return <section className="bg-bone py-28 md:py-40"><div className="page-shell"><Reveal><p className="eyebrow text-hairline">RESIDENCE TYPES</p><h2 className="display max-w-4xl text-5xl md:text-8xl">Space, clearly understood.</h2><p className="mt-6 max-w-xl text-sm text-graphite/55">Each typical level contains two two-bedroom and two three-bedroom residences. Plans are presented without invented pricing or availability.</p></Reveal><div className="mt-20 grid gap-20">{residenceTypes.slice(0,2).map((item,index)=><Reveal key={item.id} className={`grid items-center gap-10 md:grid-cols-2 ${index%2?'md:[&>*:first-child]:order-2':''}`}><button onClick={()=>setOpen(item)} className="group relative aspect-[1.35] bg-stone/30" aria-label={`Open ${item.label} plan`}><Image src={item.plan} alt={`${item.label} floor plan`} fill sizes="(min-width:768px) 50vw, 100vw" className="object-contain p-5 mix-blend-multiply transition duration-700 group-hover:scale-[1.025]"/><span className="absolute bottom-4 right-4 flex items-center gap-2 bg-bone px-3 py-2 text-[7px] uppercase tracking-[.15em]">View plan <Maximize2 size={11}/></span></button><div><p className="text-[8px] uppercase tracking-[.22em] text-hairline">0{index+1} / RESIDENCE</p><h3 className="mt-3 font-display text-5xl md:text-7xl">{item.label}</h3><p className="mt-4 text-sm text-graphite/55">{item.meta}</p><button onClick={()=>setOpen(item)} className="arrow-link mt-8">View floor plan →</button></div></Reveal>)}</div><Reveal className="mt-32"><div className="grid gap-10 md:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow text-hairline">SIGNATURE PENTHOUSES</p><h3 className="display text-5xl md:text-7xl">A different sense of scale.</h3></div><div className="relative aspect-[1.5] bg-stone/25"><Image src={cinematicAssets.residences.penthouseLevel} alt="ONA signature penthouse level overview" fill sizes="60vw" className="object-contain p-4 mix-blend-multiply"/></div></div><div className="mt-12 grid gap-px bg-graphite/15 md:grid-cols-2">{residenceTypes.slice(2).map(item=><button key={item.id} onClick={()=>setOpen(item)} className="bg-bone p-7 text-left transition hover:bg-stone/25"><p className="text-[8px] uppercase tracking-[.18em] text-hairline">{item.label}</p><h4 className="mt-2 font-display text-3xl">{item.meta}</h4><span className="mt-6 block text-[8px] uppercase tracking-widest">View plan →</span></button>)}</div></Reveal></div><AnimatePresence>{open&&<PlanViewer item={open} onClose={()=>setOpen(null)}/>}</AnimatePresence></section>}
