'use client'
import Link from 'next/link'
import {ArrowRight} from 'lucide-react'
import {Media} from '@/components/ui/Media'
import {Reveal} from '@/components/ui/Reveal'
import {BuildingJourney} from '@/components/journey/BuildingJourney'
import {StatsStrip} from './StatsStrip'
import {amenityGroups,experienceSteps,residences} from '@/lib/data'
const A=()=> <ArrowRight size={16} strokeWidth={1.5}/>
export function Home(){return <>
 <BuildingJourney/>
 <section className="bg-charcoal py-20 text-bone"><div className="page-shell flex flex-col items-start justify-between gap-10 md:flex-row md:items-end"><div><p className="eyebrow text-bone/60">THE JOURNEY CONTINUES</p><h1 className="display max-w-4xl text-6xl md:text-8xl">Choose how you want to live.</h1></div><div className="flex flex-wrap gap-3"><Link className="button-light" href="/residences">Explore Residences <A/></Link><Link className="button-ghost" href="/enquire">Enquire Now <A/></Link></div></div></section>
 <StatsStrip/>
 <section className="section-space bg-bone"><div className="page-shell"><SectionTitle tag="RESIDENCES" title="Homes measured in possibility."/><div className="mt-20 space-y-24">{residences.map((r,i)=><Reveal key={r.slug}><article className={`group grid gap-8 md:grid-cols-2 md:items-center ${i%2?'md:[&>*:first-child]:order-2':''}`}><Media src={r.image} alt={`${r.name} concept`} className="aspect-[4/3]"/><div className="md:px-10"><span className="text-xs text-hairline">0{i+1}</span><h3 className="mt-5 font-display text-5xl md:text-6xl">{r.name}</h3><p className="mt-5 text-xl">{r.size} · {r.beds}</p><div className="my-7 flex flex-wrap gap-2">{r.tags.map(t=><span className="border border-graphite/20 px-3 py-1 text-xs" key={t}>{t}</span>)}</div><Link className="arrow-link" href={`/residences/${r.slug}`}>Explore <A/></Link></div></article></Reveal>)}</div></div></section>
 <section className="section-space bg-stone"><div className="page-shell"><SectionTitle tag="PLACE" title="Modern Zanzibar, shaped from within."/><p className="mt-8 max-w-2xl text-graphite/65">Not traditional Zanzibar copied directly, but a contemporary response to its climate and ways of living.</p><div className="mt-16 grid gap-px bg-graphite/15 sm:grid-cols-2 lg:grid-cols-5">{['Shade','Breeze','Verandas','Indoor–Outdoor Living','Local Materials'].map((x,i)=><Reveal key={x} delay={i*.08}><div className="group bg-stone"><Media src={`/placeholders/${i%2?'experience':'residence-02'}.svg`} alt={`${x} concept`} className="aspect-[4/5]"/><h3 className="py-5 font-display text-3xl">{x}</h3></div></Reveal>)}</div></div></section>
 <section className="section-space bg-bone"><div className="page-shell"><SectionTitle tag="EXPERIENCE" title="A day at ONA."/><div className="scrollbar-hide mt-14 flex snap-x gap-5 overflow-x-auto pb-6">{experienceSteps.map(([t,c],i)=><article className="min-w-[82vw] snap-start border-t border-graphite/25 py-8 sm:min-w-[43vw] lg:min-w-[27vw]" key={t}><span className="text-xs text-hairline">0{i+1}</span><h3 className="mt-16 font-display text-5xl">{t}</h3><p className="mt-5 max-w-xs text-sm text-graphite/60">{c}</p></article>)}</div><Link href="/experience" className="arrow-link mt-8">Experience ONA <A/></Link></div></section>
 <section className="section-space bg-charcoal text-bone"><div className="page-shell"><SectionTitle tag="AMENITIES" title="Everything in its place."/><div className="mt-16 grid gap-px bg-bone/15 md:grid-cols-2">{amenityGroups.map((g,i)=><Link href="/amenities" className="group bg-charcoal p-7 md:p-10" key={g.title}><span className="text-xs text-hairline">0{i+1}</span><h3 className="mt-14 font-display text-5xl">{g.title}</h3><p className="mt-5 text-sm text-bone/55">{g.items.join(' · ')}</p></Link>)}</div></div></section>
 <Teaser tag="SMART LIVING" title="Technology that works quietly in the background." href="/smart-living" image="/placeholders/residence-01.svg"/><Teaser tag="LOCATION" title="Connected to Zanzibar life." href="/location" image="/placeholders/experience.svg" flip/>
 <section className="bg-charcoal py-24 text-bone"><div className="page-shell flex flex-col items-start justify-between gap-10 md:flex-row md:items-end"><h2 className="display max-w-4xl text-6xl md:text-8xl">Find your space at ONA.</h2><Link href="/enquire" className="button-light shrink-0">Enquire Now <A/></Link></div></section>
 </>}
function SectionTitle({tag,title}:{tag:string;title:string}){return <Reveal><p className="eyebrow">{tag}</p><h2 className="display max-w-5xl text-[clamp(3.6rem,7vw,7rem)]">{title}</h2></Reveal>}
function Teaser({tag,title,href,image,flip=false}:{tag:string;title:string;href:string;image:string;flip?:boolean}){return <section className="bg-bone"><div className={`grid md:grid-cols-2 ${flip?'md:[&>*:first-child]:order-2':''}`}><Media src={image} alt="Architectural concept" className="min-h-[55vh]"/><Reveal className="flex flex-col items-start justify-center px-6 py-20 md:p-16 lg:p-24"><p className="eyebrow">{tag}</p><h2 className="display text-5xl lg:text-7xl">{title}</h2><Link className="arrow-link mt-10" href={href}>Discover more <A/></Link></Reveal></div></section>}
